### PR TITLE
Add the gRPC-based transport spec.

### PR DESCRIPTION
**Pull request by danilvpetrov**
#### What change does this introduce?

This change  relocates transport spec definitions from the `github.com/dogmatiq/transportspec` repository.

#### What issues does this relate to?

Fixes https://github.com/dogmatiq/interopspec/issues/1.

#### Why make this change?

This change is required to relocate the transport spec into a dedicated package within the current repository. This change is among others to arrange and concentrate all spec definitions for the application interoperability within a single repository.

#### Is there anything you are unsure about?

Possibly the directory structure for the envelope spec within the current repository might be reviewed.

### CODE REVIEW

**Comment by jmalloc** [comment]
> Possibly the directory structure for the envelope spec within the current repository might be reviewed.

Did you have something particular in mind here?

**Comment by danilvpetrov** [comment]
No, not really, I copied this statement there from previous similar PRs just to make sure that we are ok to call the new directory `transportspec`.

**Comment by jmalloc** [comment]
Ahh ok. I had wondered if you were suggesting moving `envelopespec.Envelope` into the root, alongside `Identity`.

**Comment by danilvpetrov** [comment]
> Ahh ok. I had wondered if you were suggesting moving `envelopespec.Envelope` into the root, alongside `Identity`

That would move envelope validation code to the root too, as far as I understand. There will be nothing left in `envelopspec` directory at  all. 

Do we want to ditch `envelopespec` package alltogether?

**Comment by jmalloc** [comment]
Let's leave it as is for now. I think this PR is all good.

**Pull request merged**
